on:
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
  release:
    types: [ published, created, edited ]
  workflow_dispatch:
  schedule:
    # daily
    - cron:  '0 0 * * *'

env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_REGISTRY: ghcr.io/meta-flutter

jobs:
  login:
    name: Log in to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}
      - name: Pull image
        run: |
          docker pull ghcr.io/meta-flutter/ubuntu-20-dev:main
  build:
    env:
      YOCTO_VERSION: 3.3.2
      YOCTO_BRANCH: hardknott
    runs-on: [self-hosted, linux]
    container: 
      image: ghcr.io/meta-flutter/ubuntu-20-dev:main
    steps:
      - name: Setup permissions
        run: |
          sudo chown -R dev:dev $HOME .       
      - uses: actions/checkout@v2
        with:
          path: 'meta-flutter'
      - name: Fetch poky
        run: |
          mv poky/build/sstate-cache . || true
          rm -rf poky meta-openembedded
          git clone -b $YOCTO_BRANCH --single-branch git://git.yoctoproject.org/poky
          git clone -b $YOCTO_BRANCH --single-branch git://git.openembedded.org/meta-openembedded
      - name: Configure build
        run: |
          cd poky
          . oe-init-build-env
          mv ../../sstate-cache . || true
          bitbake-layers add-layer ../../meta-openembedded/meta-oe
          bitbake-layers add-layer ../../meta-flutter
          echo "SSTATE_MIRRORS = \"file://.* http://sstate.yoctoproject.org/$YOCTO_VERSION/PATH;downloadfilename=PATH \\n\"" >> conf/local.conf
          echo 'PREFERRED_PROVIDER_virtual/kernel = "linux-dummy"' >> conf/local.conf
      - name: Run bitbake flutter-engine
        run: |
          cd poky
          . oe-init-build-env
          bitbake flutter-engine
      - name: Run bitbake flutter-sdk
        run: |
          cd poky
          . oe-init-build-env
          bitbake flutter-sdk
      - name: Run bitbake flutter-gallery
        run: |
          cd poky
          . oe-init-build-env
          bitbake flutter-gallery
      - name: Run bitbake flutter-pi
        run: |
          cd poky
          . oe-init-build-env
          bitbake flutter-pi
